### PR TITLE
ecmd-pdbg istep control update

### PR DESCRIPTION
**Pull request by lkammath**
1. Enabled isteps proc_clock_test , set_ref_clock, sbe_config_update
2. Replaced CFAM based istep mode settings with istep_init

### CODE REVIEW

**Comment by lkammath** [comment]
@apopple @thejta @amitay please review

**Comment by lkammath** [comment]
> libekb_init() also need to call asp part ipl_init().

This will bring additional dependency of libekb to be linked which i think we can do it with seperate PR. right now we are good with current set of changes

**Comment by ojayanth** [comment]
I am fine with new PR , curently libekb_int() got minimu functionalty like adding trace support for PEL.

**Comment by apopple** [comment]
@lkammath please make sure you submit a PR to add the libekb_init() call that @ojayanth pointed out. Thanks!

**Comment by lkammath** [comment]
@apopple PR #43 will handle same. Thx

**Pull request merged**
