### PR TITLE
Fix istep 20 and 21 substeps according to ipl flow document

### PR DESCRIPTION
**Pull request by lkammath**
Fixes the istep 20 and 21 substeps as per the IPL flow document

### CODE REVIEW

**Comment by lkammath** [comment]
> {21, 5, "host_post_start_payload", EDBG_ISTEP_HOST},
> {21, 6, "switchbcu", EDBG_ISTEP_HOST},
> {21, 7, "completeipl", EDBG_ISTEP_HOST},
> 
> above steps are not host istep , this should be no-op for BMC.

Fixed

**Comment by lkammath** [comment]
Tested with PHYP load. Looks good :-)

**Comment by lkammath** [comment]
@ojayanth Dan Crowell confirmed that istep 20.2 is an HB istep and IPL flow document needs to be updated accordingly. I have changed accordingly and tested and it is good to go

@thejta FYI

**Comment by thejta** [comment]
Will merge when @ojayanth signs off

**Comment by thejta** [comment]
@dcrowell77 signing off works too.  Merged it.

**Pull request merged**
